export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const AUTHORIZE_ATTEMPT = 'AUTHORIZE_ATTEMPT';
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCESS';

export const SET_MESSAGE = 'SET_MESSAGE';
export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';

export const SET_ERRORS = 'SET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';

export const FETCH_ARTICLES_LIST_SUCCESS = 'FETCH_ARTICLES_LIST_SUCCESS';
export const FETCH_ARTICLES_LIST_FAIL = 'FETCH_ARTICLES_LIST_FAIL';
export const FETCH_ARTICLES_LIST_REQUEST = 'FETCH_ARTICLES_LIST_REQUEST';

export const FETCH_ARTICLE_SUCCESS = 'FETCH_ARTICLE_SUCCESS';
export const FETCH_ARTICLE_FAIL = 'FETCH_ARTICLE_FAIL';
export const FETCH_ARTICLE_REQUEST = 'FETCH_ARTICLE_REQUEST';

export const DELETE_ARTICLE_SUCCESS = 'DELETE_ARTICLE_SUCCESS';
export const DELETE_ARTICLE_FAIL = 'DELETE_ARTICLE_FAIL';
export const DELETE_ARTICLE_REQUEST = 'DELETE_ARTICLE_REQUEST';

export const CREATE_ARTICLE_SUCCESS = 'CREATE_ARTICLE_SUCCESS';
export const CREATE_ARTICLE_FAIL = 'CREATE_ARTICLE_FAIL';

export const UPDATE_ARTICLE_SUCCESS = 'UPDATE_ARTICLE_SUCCESS';
export const UPDATE_ARTICLE_FAIL = 'UPDATE_ARTICLE_FAIL';

export const LIKE_ARTICLE_SUCCESS = 'LIKE_ARTICLE_SUCCESS';
export const LIKE_ARTICLE_FAIL = 'LIKE_ARTICLE_FAIL';

export const UNLIKE_ARTICLE_SUCCESS = 'UNLIKE_ARTICLE_SUCCESS';
export const UNLIKE_ARTICLE_FAIL = 'UNLIKE_ARTICLE_FAIL';

export const CLEAR_ARTICLE = 'CLEAR_ARTICLE';

export const SET_LOADING = 'SET_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';

export const CLEAR_REDIRECT = 'CLEAR_REDIRECT';
export const NEED_REDIRECT = 'NEED_REDIRECT';
